<a href="https://colab.research.google.com/github/mehak132002/movie_recommendation/blob/main/movie_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libraries

In [3]:
import numpy as np
import pandas as pd
import difflib # get the closest match to the user input in case of wrong input given by user
from sklearn.feature_extraction.text import TfidfVectorizer # convert textual data to numerical data
from sklearn.metrics.pairwise import cosine_similarity # to find similarities b/w movies

In [4]:
#unzipping of files
from zipfile import ZipFile
dataset = '/content/tmdb_5000_credits.csv.zip'

with ZipFile('tmdb_5000_credits.csv.zip' , 'r') as zip:
  zip.extractall()
  print("credits extracted")

dataset = '/content/tmdb_5000_movies.csv.zip'

with ZipFile('tmdb_5000_movies.csv.zip' , 'r') as zip:
  zip.extractall()
  print("movies extracted")

credits extracted
movies extracted


In [5]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [6]:
movies.head(1)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                       tagline   title  vote_average  vote_count  
0  Enter the World of Pandora.  Avatar           7.2       11800

In [7]:
credits.head(1)

movie_id   title                                               cast  \
0     19995  Avatar  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...

In [8]:
credits.head(1)['cast'].values

array(['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "ge

In [9]:
#merging both dataframes on basis of title
movies.merge(credits, on = 'title' ).shape

(4809, 23)

In [10]:
movies = movies.merge(credits, on = 'title' )

In [11]:
movies.head(1)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies  ... runtime  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                       tagline   title vote_average vote_count movie_id  \
0  Enter the World of Pandora.  Avatar          7.2      11800    19995   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  

[1 rows x 23 columns]

In [12]:
#column that we will keep
#geners
#keywords
#title
#overview
#cast
#crew
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [13]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

# Data Preprocessing

In [14]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [15]:
# dropping the 3 movies w/o overview
movies.dropna(inplace = True)

In [16]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [17]:
#checking if duplicates exists
movies.duplicated().sum()

0

In [18]:
movies.iloc[0].genres
# 'action' , 'adventure' , 'fantasy' , 'science fiction'

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [19]:
import ast
def convert(obj):
  l = []
  for i in ast.literal_eval(obj) :
    l.append(i['name'])
    return l

In [20]:
movies['genres'] = movies['genres'].apply(convert)

In [21]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  In the 22nd century, a paraplegic Marine is di...     [Action]   
1  Captain Barbossa, long believed to be dead, ha...  [Adventure]   
2  A cryptic message from Bond’s past sends him o...     [Action]   
3  Following the death of District Attorney Harve...     [Action]   
4  John Carter is a war-weary, former military ca...     [Action]   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [22]:
movies['keywords'] = movies['keywords'].apply(convert)

In [23]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  In the 22nd century, a paraplegic Marine is di...     [Action]   
1  Captain Barbossa, long believed to be dead, ha...  [Adventure]   
2  A cryptic message from Bond’s past sends him o...     [Action]   
3  Following the death of District Attorney Harve...     [Action]   
4  John Carter is a war-weary, former military ca...     [Action]   

           keywords                                               cast  \
0   [culture clash]  [{"cast_id": 242, "character": "Jake Sully", "...   
1           [ocean]  [{"cast_id": 4, "character": "Captain Jack Spa...   
2             [spy]  [{"cast_id": 1, "character": "James Bond", "cr...   
3       [dc comics]  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [based on novel]  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [24]:
def convertcast(obj):
  l = []
  counter = 0
  for i in ast.literal_eval(obj) :
    if counter != 3 :
      l.append(i['name'])
      counter+=1
    else:
      break
  return l

In [25]:
movies['cast'] = movies['cast'].apply(convertcast)

In [26]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  In the 22nd century, a paraplegic Marine is di...     [Action]   
1  Captain Barbossa, long believed to be dead, ha...  [Adventure]   
2  A cryptic message from Bond’s past sends him o...     [Action]   
3  Following the death of District Attorney Harve...     [Action]   
4  John Carter is a war-weary, former military ca...     [Action]   

           keywords                                              cast  \
0   [culture clash]  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   
1           [ocean]     [Johnny Depp, Orlando Bloom, Keira Knightley]   
2             [spy]      [Daniel Craig, Christoph Waltz, Léa Seydoux]   
3       [dc comics]      [Christian Bale, Michael Caine, Gary Oldman]   
4  [based on novel]    [Taylor Kitsch, Lynn Collins, Samantha Morton]   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [27]:
import ast
def get_director(obj):
  l = []
  if not obj or obj == '[]':  # Handle empty strings or empty lists
    return l
  for i in ast.literal_eval(obj) :
    if i['job'] == 'Director':
      l.append(i['name'])
      break
  return l

In [28]:
movies['crew'] = movies['crew'].apply(get_director)

In [29]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  In the 22nd century, a paraplegic Marine is di...     [Action]   
1  Captain Barbossa, long believed to be dead, ha...  [Adventure]   
2  A cryptic message from Bond’s past sends him o...     [Action]   
3  Following the death of District Attorney Harve...     [Action]   
4  John Carter is a war-weary, former military ca...     [Action]   

           keywords                                              cast  \
0   [culture clash]  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   
1           [ocean]     [Johnny Depp, Orlando Bloom, Keira Knightley]   
2             [spy]      [Daniel Craig, Christoph Waltz, Léa Seydoux]   
3       [dc comics]      [Christian Bale, Michael Caine, Gary Oldman]   
4  [based on novel]    [Taylor Kitsch, Lynn Collins, Samantha Morton]   

                  crew  
0      [James Cameron]  
1     [Gore Verbinski]  
2         [Sam Mendes]  
3  [Christopher Nolan]  
4     [Andrew Stanton]

In [30]:
movies['overview'] = movies['overview'].apply(lambda x :x.split())

In [31]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...     [Action]   
1  [Captain, Barbossa,, long, believed, to, be, d...  [Adventure]   
2  [A, cryptic, message, from, Bond’s, past, send...     [Action]   
3  [Following, the, death, of, District, Attorney...     [Action]   
4  [John, Carter, is, a, war-weary,, former, mili...     [Action]   

           keywords                                              cast  \
0   [culture clash]  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   
1           [ocean]     [Johnny Depp, Orlando Bloom, Keira Knightley]   
2             [spy]      [Daniel Craig, Christoph Waltz, Léa Seydoux]   
3       [dc comics]      [Christian Bale, Michael Caine, Gary Oldman]   
4  [based on novel]    [Taylor Kitsch, Lynn Collins, Samantha Morton]   

                  crew  
0      [James Cameron]  
1     [Gore Verbinski]  
2         [Sam Mendes]  
3  [Christopher Nolan]  
4     [Andrew Stanton]

In [32]:
# removing spaces from within the words and making them single long word.
movies['genres'] = movies['genres'].apply(lambda x:[i.replace (" ", "") for i in x] if x is not None else [])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace (" ", "") for i in x] if x is not None else [])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace (" ", "") for i in x] if x is not None else [])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace (" ", "") for i in x] if x is not None else [])

In [33]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...     [Action]   
1  [Captain, Barbossa,, long, believed, to, be, d...  [Adventure]   
2  [A, cryptic, message, from, Bond’s, past, send...     [Action]   
3  [Following, the, death, of, District, Attorney...     [Action]   
4  [John, Carter, is, a, war-weary,, former, mili...     [Action]   

         keywords                                           cast  \
0  [cultureclash]  [SamWorthington, ZoeSaldana, SigourneyWeaver]   
1         [ocean]     [JohnnyDepp, OrlandoBloom, KeiraKnightley]   
2           [spy]      [DanielCraig, ChristophWaltz, LéaSeydoux]   
3      [dccomics]      [ChristianBale, MichaelCaine, GaryOldman]   
4  [basedonnovel]    [TaylorKitsch, LynnCollins, SamanthaMorton]   

                 crew  
0      [JamesCameron]  
1     [GoreVerbinski]  
2         [SamMendes]  
3  [ChristopherNolan]  
4     [AndrewStanton]

In [34]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [35]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview       genres  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...     [Action]   
1  [Captain, Barbossa,, long, believed, to, be, d...  [Adventure]   
2  [A, cryptic, message, from, Bond’s, past, send...     [Action]   
3  [Following, the, death, of, District, Attorney...     [Action]   
4  [John, Carter, is, a, war-weary,, former, mili...     [Action]   

         keywords                                           cast  \
0  [cultureclash]  [SamWorthington, ZoeSaldana, SigourneyWeaver]   
1         [ocean]     [JohnnyDepp, OrlandoBloom, KeiraKnightley]   
2           [spy]      [DanielCraig, ChristophWaltz, LéaSeydoux]   
3      [dccomics]      [ChristianBale, MichaelCaine, GaryOldman]   
4  [basedonnovel]    [TaylorKitsch, LynnCollins, SamanthaMorton]   

                 crew                                               tags  
0      [JamesCameron]  [In, the, 22nd, century,, a, paraplegic, Marin...  
1     [GoreVerbinski]  [Captain, Barbossa,, long, believed, to, be, d...  
2         [SamMendes]  [A, cryptic, message, from, Bond’s, past, send...  
3  [ChristopherNolan]  [Following, the, death, of, District, Attorney...  
4     [AndrewStanton]  [John, Carter, is, a, war-weary,, former, mili...

In [36]:
new_df = movies[['movie_id','title','tags']]

In [37]:
new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

<ipython-input-37-fe97dfee7549>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))


In [38]:
new_df.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [39]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action cultureclash SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [40]:
#convert to lower case
new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())

<ipython-input-40-2950f185b4d8>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())


In [41]:
new_df.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  in the 22nd century, a paraplegic marine is di...  
1  captain barbossa, long believed to be dead, ha...  
2  a cryptic message from bond’s past sends him o...  
3  following the death of district attorney harve...  
4  john carter is a war-weary, former military ca...

# Vectorization

Bag-of-Words

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features= 5000 , stop_words = 'english')

In [43]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [44]:
print(vectors)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [45]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [46]:
# [love , loving , loved ] -> love : Stemming
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [47]:
def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)


In [48]:
new_df['tags'] = new_df['tags'].apply(stem)

<ipython-input-48-be18a4346d89>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)


In [49]:
#calculate distance to nearest movie and based on distance find similarites .
#we will use cosine distance i.e angle b/w the vectors.
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [50]:
similarity[0]

array([1.        , 0.        , 0.04902903, ..., 0.        , 0.        ,
       0.        ])

# Main Function

In [51]:
movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : tangled


In [52]:
list_of_all_titles = new_df['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [53]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Tangled', 'Triangle', 'Stranded']


In [54]:
close_match = find_close_match[0]
print(close_match)

Tangled


In [55]:
index_of_the_movie = new_df[new_df['title'] == close_match].index[0]
print(index_of_the_movie)

6


In [56]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.03857583749052298), (1, 0.0), (2, 0.030261376633440123), (3, 0.06241877839323594), (4, 0.0563436169819011), (5, 0.0), (6, 1.0000000000000002), (7, 0.05372153093502536), (8, 0.0), (9, 0.052164053095730106), (10, 0.0), (11, 0.0), (12, 0.0), (13, 0.09759000729485333), (14, 0.030860669992418384), (15, 0.0), (16, 0.0), (17, 0.0), (18, 0.0419960525565808), (19, 0.024397501823713332), (20, 0.037151880838356854), (21, 0.030261376633440123), (22, 0.0), (23, 0.0), (24, 0.030261376633440123), (25, 0.019596545041740514), (26, 0.0), (27, 0.0), (28, 0.08559209850218259), (29, 0.046004370622823615), (30, 0.026082026547865053), (31, 0.0363696483726654), (32, 0.0), (33, 0.0), (34, 0.042796049251091296), (35, 0.0), (36, 0.027713699773684666), (37, 0.0), (38, 0.040177170184515394), (39, 0.029695693545824933), (40, 0.031497039417435604), (41, 0.0), (42, 0.13041013273932528), (43, 0.027713699773684666), (44, 0.046524210519923545), (45, 0.044543540318737404), (46, 0.03289758474798845), (47, 0.0218217

In [57]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(6, 1.0000000000000002), (4683, 0.17251638983558854), (94, 0.15936381457791915), (4405, 0.1543033499620919), (1293, 0.15130688316720062), (1044, 0.1454785934906616), (1476, 0.13957263155977062), (3077, 0.1336306209562122), (42, 0.13041013273932528), (1252, 0.12717117101978923), (2366, 0.12683657235796025), (4516, 0.12598815766974242), (506, 0.12371791482634838), (1990, 0.12309149097933272), (950, 0.12198750911856666), (538, 0.11952286093343936), (2645, 0.11952286093343936), (2786, 0.11952286093343936), (2970, 0.11952286093343936), (283, 0.11878277418329973), (67, 0.11664236870396086), (164, 0.11664236870396086), (4688, 0.11572751247156893), (660, 0.11227217828476796), (1520, 0.11227217828476796), (2925, 0.11227217828476796), (3824, 0.11227217828476796), (4472, 0.11227217828476796), (255, 0.11085479909473867), (1062, 0.10910894511799621), (1098, 0.10910894511799621), (1658, 0.10910894511799621), (2916, 0.10910894511799618), (3888, 0.10910894511799618), (4636, 0.10910894511799618), (204

In [58]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = new_df[new_df.index==index]['title'].values
  #
  if (i<6):
    print(i, '',title_from_index)
    i+=1


Movies suggested for you : 

1  ['Tangled']
2  ['Three']
3  ['Guardians of the Galaxy']
4  ['Special']
5  ['Baahubali: The Beginning']


In [60]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = new_df['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = new_df[new_df['title'] == close_match].index[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = new_df[new_df.index==index]['title'].values
  if (i<7):
    print(i-1, '.',title_from_index)
    i+=1

 Enter your favourite movie name : batman begins
Movies suggested for you : 

0 . ['Batman Begins']
1 . ['The Dark Knight Rises']
2 . ['Raising Helen']
3 . ['The Dark Knight']
4 . ['Batman Forever']
5 . ['Synecdoche, New York']
